import React, { useState, useCallback } from 'react';
import { generateImage } from '../services/geminiService';
import { ImageIcon, SparklesIcon } from './Icons';
import Spinner from './Spinner';

const ImageGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState<string>('A stylized, artistic photo of a hopeful young chick emerging from a golden egg.');
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = useCallback(async () => {
    if (!prompt) {
      setError('Please enter a prompt.');
      return;
    }

    setIsLoading(true);
    setError(null);
    setImageUrl(null);

    try {
      const url = await generateImage(prompt);
      setImageUrl(url);
    } catch (err) {
      setError('Failed to generate image. Please try a different prompt.');
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  }, [prompt]);

  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-bold text-gray-700">AI Image Generator</h2>
      <p className="text-gray-600">
        Use the power of AI to generate unique images related to poultry, eggs, or anything you can imagine. Describe what you want to see below.
      </p>

      <div className="space-y-2">
        <label htmlFor="prompt" className="text-lg font-semibold text-gray-700">Image Description</label>
        <textarea
          id="prompt"
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="e.g., A futuristic poultry farm with happy, healthy chickens"
          className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-amber-500 focus:border-amber-500 transition-shadow"
          rows={3}
        />
      </div>

      <button
        onClick={handleGenerate}
        disabled={isLoading || !prompt}
        className="w-full sm:w-auto flex items-center justify-center gap-2 bg-amber-500 text-white font-bold py-3 px-6 rounded-lg hover:bg-amber-600 disabled:bg-gray-300 transition-colors"
      >
        {isLoading ? <><Spinner /> Generating...</> : <><SparklesIcon className="w-5 h-5" /> Generate Image</>}
      </button>

      <div className="mt-6">
        <h3 className="text-lg font-semibold text-gray-700">Generated Image</h3>
        <div className="w-full mt-2 bg-gray-50 rounded-lg p-4 min-h-[20rem] border border-gray-200 flex items-center justify-center">
          {error && <p className="text-red-500">{error}</p>}
          {isLoading && <Spinner size="lg" />}
          {!isLoading && !imageUrl && !error && <ImageIcon className="w-24 h-24 text-gray-300" />}
          {imageUrl && (
            <img src={imageUrl} alt="Generated by AI" className="rounded-lg shadow-lg w-full h-auto max-h-96 object-contain" />
          )}
        </div>
      </div>
    </div>
  );
};

export default ImageGenerator;